name: frontend
description: "An ERP a an CRM to dental clinics"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  awesome_extensions: ^2.0.20
  brasil_fields: ^1.17.0
  build_runner: ^2.4.15
  calendar_view: ^1.4.0
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.18
  dash_flags: ^0.1.1
  datepicker_dropdown: ^0.1.7
  drag_and_drop_lists: ^0.4.2
  dio: ^5.4.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_multi_formatter: ^2.13.7
  flutter_svg: ^2.1.0
  flutter_reorderable_list: ^1.3.1
  font_awesome_flutter: ^10.8.0
  form_field_validator: ^1.1.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  horizontal_calendar: ^1.1.2
#  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  kanban_board: ^1.0.0+2
  mask_text_input_formatter: ^2.9.0
  number_pagination: ^1.1.6
  panara_dialogs: ^0.1.5
  provider: ^6.1.2
  retrofit: ^4.4.2
  responsive_builder: ^0.7.1
#  syncfusion_flutter_calendar: ^28.2.7
  searchable_listview: ^2.17.3
  syncfusion_flutter_datepicker: ^28.2.4
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0+3
  timeline_tile: ^2.0.0
  toastification: ^3.0.2
  toggle_switch: ^2.3.0

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  dio: 5.4.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  retrofit_generator: ^9.2.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/.env
    - assets/.env.dev
    - assets/.env.local
    - assets/GetItOnGooglePlayPtBr.png
    - assets/countries_states_and_cities/portugal.json
    - assets/countries_states_and_cities/brazil.json
    - assets/logo/amplify_black.svg
    - assets/logo/amplify_white.svg
    - assets/logo/amplify_dark_gray.svg
    - assets/logo/amplify_light_gray.svg
    - assets/logo/amplify_primary_green.svg
    - assets/logo/amplify_secondary_green.svg
    - assets/logo/amplify_gradient.svg
    - assets/dental_arch.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

